# Generated by Django 3.2.6 on 2021-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_auto_20210803_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_cnt',
            field=models.IntegerField(default=0),
        ),
    ]
